name = "projetos-fortran"
version = "0.1.0"
license = "MIT"  # Use MIT ou outro tipo de licença, mas "license" não é válido
author = "Alan Ryan da Silva Domingues"
maintainer = "alanryan619@gmail.com"
copyright = "Copyright 2025, Alan Ryan da Silva Domingues"

[build]
auto-executables = true    
auto-tests = true      
auto-examples = true     
module-naming = false    

[install]
library = false         

[fortran]
implicit-typing = false   
implicit-external = false 
source-form = "free"       